[package]
name = "example"
version = "0.1.0"
authors = ["Christopher Prohm <mail@cprohm.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
arrow = "15.0.0"
serde = { version = "1.0.137", features = ["derive"] }

serde_arrow = { path = "../serde_arrow" }
serde_json = "1.0.81"
